# Generated by Django 6.0.1 on 2026-01-31 03:18

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Counter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('branch', models.CharField(choices=[('mota_varachha', 'Mota Varachha'), ('hirabaug', 'Hirabaug'), ('abrama', 'Abrama')], max_length=50, unique=True)),
                ('value', models.IntegerField(default=0)),
            ],
        ),
    ]
